# Extension configuration file.
# Visit the "Extension configuration file (extension.toml)" section for more details:
# https://docs.omniverse.nvidia.com/kit/docs/kit-manual/latest/guide/extensions_advanced.html
#

[core]
reloadable = true
order = 0

[package]
version = "0.1.0"
category = "graph"
title = "Isaac_PX4sitl_Bridge"
description = "a custom bridge for px4_sitl and isaacsim"
authors = ["labeeb"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/beluga.png"
icon = "data/beluga.png"

[[python.module]]
name = "isaac.px4_sitl.bridge"

[dependencies]
"omni.graph.core" = {}
"omni.graph.tools" = {}

[[native.plugin]]
path = "bin/*.plugin"

[settings]
exts."isaac.px4_sitl.bridge".timeout = 5

